<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LoperFamilyTreeBuilder.ImportExport</AssemblyName>
    <RootNamespace>LoperFamilyTreeBuilder.ImportExport</RootNamespace>
  </PropertyGroup>
</Project>
